<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [1]:
import os

In [2]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo1-leccion01-manejo-errores.ipynb',
 'laboratorio-modulo1-leccion01-break-pass-continue.ipynb',
 'laboratorio-modulo1-leccion02-clases.ipynb']

In [4]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 7.4 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 24.1.1 -> 24.3.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [5]:
import numpy as np

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [12]:
array_unidimensional = np.arange(10)

print(f"El array 1D creado es: {array_unidimensional}")

El array 1D creado es: [0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [15]:
lista_bidimensional = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

array_bidimensional = np.array(lista_bidimensional)

print(f"El array 2D creado es:")
print(array_bidimensional)

El array 2D creado es:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [23]:
array = np.array([0,2,0,3,0,4,0])

print(array)

resultado = np.where(array != 0)

print(resultado)

[0 2 0 3 0 4 0]
(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [30]:
array_3x3_random = np.random.rand(3,3)

print(array_3x3_random)

[[0.65874147 0.76828016 0.07795829]
 [0.7012462  0.67994941 0.17200068]
 [0.76745937 0.64047594 0.62795623]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [34]:
array_10_numeros = np.random.rand(10)

print(array_10_numeros)

valor_maximo = np.max(array_10_numeros)
valor_minimo = np.min(array_10_numeros)

print("_______________________")
print(f"El valor máximo del array es {valor_maximo} y el mínimo {valor_minimo}")


[0.75154489 0.07380292 0.0056823  0.07134415 0.64177567 0.80293799
 0.35908747 0.95731429 0.12443016 0.27264428]
_______________________
El valor máximo del array es 0.957314292504941 y el mínimo 0.005682303975463876


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [45]:
array_invertir = np.random.rand(5)

array_invertido = np.flip(array_invertir)

print(f"El array que queremos invertir es: {array_invertir}")
print("____________________")

print(f"El array invertido es {array_invertido}")

El array que queremos invertir es: [0.70565334 0.91351411 0.07906364 0.32980783 0.75240262]
____________________
El array invertido es [0.75240262 0.32980783 0.07906364 0.91351411 0.70565334]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [54]:
array_tridimensional = np.random.randint(1, 24, (2,3, 4))
print(array_tridimensional)

[[[14  3 15 10]
  [ 9 13 16 22]
  [17 15 21 22]]

 [[ 3 15 20 11]
  [ 5  9 17  4]
  [ 2  4 16 18]]]


In [59]:
# - Selecciona el primer `15` del array.
print(array_tridimensional[0,0,2])

print("_______________")

#- Selecciona todos los elementos del primer array. 
print(array_tridimensional[0])

print("_______________")

# - Selecciona la última fila del último array
print(array_tridimensional[1,2])

15
_______________
[[14  3 15 10]
 [ 9 13 16 22]
 [17 15 21 22]]
_______________
[ 2  4 16 18]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [65]:
array_tri1 = np.random.randint(1,30,(3,2,5))

print(array_tri1)

[[[16 25 13 21  5]
  [13 28  2  8  9]]

 [[ 3 24 27  5 23]
  [ 7 15  9  6 10]]

 [[26 16 24 29 25]
  [ 3 21 24  7 16]]]


In [76]:
#- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.
print(array_tri1[0, :, :2])

print("_______________")
#- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.
print(array_tri1[1:,:,:])

[[16 25]
 [13 28]]
_______________
[[[ 3 24 27  5 23]
  [ 7 15  9  6 10]]

 [[26 16 24 29 25]
  [ 3 21 24  7 16]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [77]:
array_tri2 = np.random.randint(1,24,(4,3,2))

print(array_tri2)

[[[23 21]
  [ 8 22]
  [ 1 15]]

 [[23  2]
  [21 11]
  [18 23]]

 [[ 1 19]
  [ 5 11]
  [11 10]]

 [[ 1 18]
  [13  4]
  [17 19]]]


In [84]:
#- Cambia todos los elementos de la segunda fila del segundo array por `0`.
array_tri2[1,1,:] = 0
print(array_tri2)

print("_______________")

#- Cambia todos los valores del último array a `-1`.
array_tri2[3,:,:] = -1
print(array_tri2)

[[[23 21]
  [ 8 22]
  [ 1 15]]

 [[23  2]
  [ 0  0]
  [18 23]]

 [[ 1 19]
  [ 5 11]
  [11 10]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]
_______________
[[[23 21]
  [ 8 22]
  [ 1 15]]

 [[23  2]
  [ 0  0]
  [18 23]]

 [[ 1 19]
  [ 5 11]
  [11 10]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
array_tri3 = np.random.randint(-10,13,(2,4,3))
print(array_tri3)

[[[ -6  -6  -4]
  [  7  -6   7]
  [  1  -7  -3]
  [ -9  -4  11]]

 [[-10   0   7]
  [ -4  11  -8]
  [ -9  -1   3]
  [ -4  -1   8]]]


In [91]:
#- Selecciona todos los elementos mayores a `5`.
elementos_mayores_5 = array_tri3[(array_tri3 > 5)]
print(f"Los elementos del array mayores de 5 son:")
print(elementos_mayores_5)


print("_______________")
#- Reemplaza todos los elementos negativos por `0`.
array_tri3[array_tri3 < 0] = 0
print(array_tri3)

Los elementos del array mayores de 5 son:
[ 7  7 11  7 11  8]
_______________
[[[ 0  0  0]
  [ 7  0  7]
  [ 1  0  0]
  [ 0  0 11]]

 [[ 0  0  7]
  [ 0 11  0]
  [ 0  0  3]
  [ 0  0  8]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [92]:
array_tri4 = np.random.randint(1,27,(3,3,3))
print(array_tri4)

[[[ 6 18 13]
  [18  8 26]
  [15  9  6]]

 [[ 8 22  5]
  [17 15 24]
  [ 8  8 16]]

 [[19  9 24]
  [ 2 17  6]
  [26 12 14]]]


In [102]:
#- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.
print(array_tri4[1,:,:2])

print("_____")

#- Selecciona todos los elementos del tercer array que sean mayores que `20`.
tercer_array = array_tri4[2]

mayores_20 = tercer_array[(tercer_array > 20)]
print(f"Los elementos del tercer array mayores que 20 son: {mayores_20}")

[[ 8 22]
 [17 15]
 [ 8  8]]
_____
Los elementos del tercer array mayores que 20 son: [24 26]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [114]:
array10 = np.random.rand(10)
print(array10)

[0.29138407 0.42759599 0.57689703 0.12710689 0.71155426 0.68185114
 0.55113082 0.69802566 0.5483533  0.71880697]


In [115]:
valor_maximo = np.max(array10)
valor_minimo = np.min(array10)

array10[array10 == valor_maximo] = 0
array10[array10 == valor_minimo] = 0

print(array10)

[0.29138407 0.42759599 0.57689703 0.         0.71155426 0.68185114
 0.55113082 0.69802566 0.5483533  0.        ]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [118]:
array15 = np.random.randint(1,100, 15)

array15

array([93,  4, 52, 13, 34, 53, 89, 63, 71, 71, 51, 50, 72, 53, 63])

In [120]:
array_ordenado = np.sort(array15)

array_ordenado

array([ 4, 13, 34, 50, 51, 52, 53, 53, 63, 63, 71, 71, 72, 89, 93])

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [123]:
matriz = np.random.randint(0,10, (4,4))
matriz

array([[9, 5, 8, 9],
       [8, 7, 4, 5],
       [4, 3, 4, 2],
       [5, 6, 8, 4]])

In [125]:
suma_elementos = np.sum(matriz)

print(f"La suma de los elementos de las filas y columnas de la matriz es {suma_elementos}")

La suma de los elementos de las filas y columnas de la matriz es 91


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [127]:
matriz1 = np.zeros((5,5), dtype=int)
matriz1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [129]:
matriz1[0,:] = 1
matriz1[4,:] = 1
matriz1[:, 0] = 1
matriz1[:,4] = 1

print(matriz1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [134]:
array_media = np.random.rand(10)
print(array_media)

print("_____________")

media = np.mean(array_media)

print(f"La media del array es {media}")
      
desviacion_estandar = np.std(array_media)
print(f"La desviación estandar del array es {desviacion_estandar}")

[0.92240996 0.6651014  0.53837898 0.05871135 0.67252161 0.41881881
 0.24997946 0.74991748 0.88312755 0.21300374]
_____________
La media del array es 0.5371970342928618
La desviación estandar del array es 0.27902289474841446


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [137]:
arraytri5 = np.random.randint(1,24,(2,3,4))
arraytri5

array([[[10, 13, 10, 14],
        [ 8,  2,  4,  7],
        [19,  5, 17, 21]],

       [[ 5,  1,  8, 11],
        [21,  6, 18, 19],
        [ 4,  5,  7, 10]]])

In [ ]:
#- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).
transposicion = np.transpose(arraytri5, (2,1,0))
transposicion
#- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 

array([[[10,  5],
        [ 8, 21],
        [19,  4]],

       [[13,  1],
        [ 2,  6],
        [ 5,  5]],

       [[10,  8],
        [ 4, 18],
        [17,  7]],

       [[14, 11],
        [ 7, 19],
        [21, 10]]])


El array dado es de dimensiones 2,3,4 y queremos pasarlo a 4,3,2, por lo que hacemos es lo siguiente: 

2 3 4
4 3 2

siendo 0, la matriz
1 las filas
2 las columnas

Hacemos coincidir cada uno de los números para saber dónde colocamos cada uno de ellos: 
2: En el primer array está en la posición 0 y en el nuevo en la 2, por lo que pasaremos a poner el 0 al final del todo.
3: Está en la posición central por lo que lo dejaremos como está
4: Pasa de la posición 2 a la 0, por lo que lo pondremos al principio

las dimensiones finales son, 2,1,0 que es lo que colocaremos en el transpose.


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [142]:
arraytri6 = np. random.randint(1,24,(3,4,2))
arraytri6

array([[[ 7,  8],
        [14,  7],
        [21,  3],
        [14, 19]],

       [[23, 16],
        [ 1,  9],
        [ 6, 22],
        [ 2,  9]],

       [[20, 13],
        [ 8,  8],
        [ 3, 22],
        [ 8, 21]]])

In [144]:
# - Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).
transposicion1 = np.transpose(arraytri6, (1, 0,2))
transposicion1

array([[[ 7,  8],
        [23, 16],
        [20, 13]],

       [[14,  7],
        [ 1,  9],
        [ 8,  8]],

       [[21,  3],
        [ 6, 22],
        [ 3, 22]],

       [[14, 19],
        [ 2,  9],
        [ 8, 21]]])

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [146]:
arraytri7 = np.random.randint(1,24,(3,2,4))
arraytri7

array([[[14,  4, 17,  9],
        [21, 11,  9,  1]],

       [[23,  9,  5,  3],
        [20, 15, 23,  6]],

       [[14,  1,  9, 16],
        [18,  9, 21, 22]]])

In [147]:
#- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).
transposicion2 = np.transpose(arraytri7, (2,0,1))
print(transposicion2)

[[[14 21]
  [23 20]
  [14 18]]

 [[ 4 11]
  [ 9 15]
  [ 1  9]]

 [[17  9]
  [ 5 23]
  [ 9 21]]

 [[ 9  1]
  [ 3  6]
  [16 22]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [157]:
arraytri8 = np.random.randint(-10,10,(3,4,5))
print(arraytri5)

array_vacio = np.empty((3, 4, 5), dtype=str)

[[[10 13 10 14]
  [ 8  2  4  7]
  [19  5 17 21]]

 [[ 5  1  8 11]
  [21  6 18 19]
  [ 4  5  7 10]]]


In [159]:
mediana = np.median(arraytri8)
maximo = np.max(arraytri8)
minimo = np.min(arraytri8)

for matriz in range(arraytri8.shape[0]):
    for filas in range(arraytri8.shape[1]):
        for columnas in range(arraytri8.shape[2]):
            valor = arraytri8[matriz, filas, columnas]
            if valor == mediana:
                array_vacio[matriz, filas, columnas] = "M"
            elif valor > mediana:
                array_vacio[matriz,filas,columnas] = "X"
            elif valor < mediana:
                array_vacio[matriz,filas,columnas] = "Y"
            elif valor == maximo:
                 array_vacio[matriz,filas,columnas] = "MAX"
            elif valor == minimo:
                 array_vacio[matriz,filas,columnas] = "MIN"
            else:
                pass

print(array_vacio)

[[['X' 'Y' 'X' 'Y' 'X']
  ['Y' 'X' 'M' 'Y' 'Y']
  ['M' 'Y' 'Y' 'X' 'M']
  ['Y' 'Y' 'Y' 'Y' 'Y']]

 [['Y' 'X' 'X' 'Y' 'X']
  ['X' 'Y' 'M' 'X' 'X']
  ['X' 'Y' 'X' 'X' 'Y']
  ['Y' 'Y' 'Y' 'X' 'X']]

 [['Y' 'Y' 'X' 'Y' 'X']
  ['Y' 'X' 'Y' 'X' 'X']
  ['X' 'X' 'X' 'Y' 'X']
  ['X' 'X' 'X' 'X' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [165]:
lista_bidimensional1 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

array_bidimensional1 = np.array(lista_bidimensional1)

array_bidimensional1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

La fila [1 2 3 4 5] es igual a la columna [np.int64(1), np.int64(6)]


IndexError: list index out of range